<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:types="http://www.regione.marche.it/intermediamarche/fatturazione/attiva/services/types"
        xmlns:tns="http://www.regione.marche.it/intermediamarche/fatturazione/attiva/services"
        targetNamespace="http://www.regione.marche.it/intermediamarche/fatturazione/attiva/services">
        <!--xmlns:tns="http://www.fatturapa.gov.it/sdi/ws/trasmissione/v1.0"-->

    <!-- TIPI -->
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.regione.marche.it/intermediamarche/fatturazione/attiva/services/types" schemaLocation="../xsd/InoltroFatturazioneAttiva.xsd"/>
        </xsd:schema>
    </wsdl:types>

    <!-- MESSAGGI -->
    <wsdl:message name="RiceviFileCAMsg">
        <wsdl:part name="parametersIn" element="types:RiceviFileCAElement"/>
    </wsdl:message>

    <wsdl:message name="RispostaRiceviFileCAMsg">
        <wsdl:part name="parametersOut" element="types:RispostaRiceviFileCAElement"/>
    </wsdl:message>
    
    <wsdl:message name="RispostaRiceviFileCAMsgFault">
        <wsdl:part name="parametersOut" element="types:FaultDetail"/>
    </wsdl:message>
    
    <!-- PORT TYPE -->
     <wsdl:portType name="RiceviFileCAPort">
        <wsdl:operation name="RiceviFileCA">
            <wsdl:input message="tns:RiceviFileCAMsg"/>
            <wsdl:output message="tns:RispostaRiceviFileCAMsg"/>
            <wsdl:fault name="RispostaRiceviFileCAMsgFault" message="tns:RispostaRiceviFileCAMsgFault" />
        </wsdl:operation>
    </wsdl:portType>

    <!-- PORT BINDING -->
    <wsdl:binding name="RiceviFileCABinding" type="tns:RiceviFileCAPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="RiceviFileCA">
            <soap:operation soapAction="inoltroFatturaAttiva"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="RispostaRiceviFileCAMsgFault">
                <soap:fault name="RispostaRiceviFileCAMsgFault" use="literal" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:service name="RiceviFileCAService">
        <wsdl:port name="RiceviFileCAPort" binding="tns:RiceviFileCABinding">
            <soap:address location="http://www.regione.marche.it/intermediamarche/fatturaAttiva/fatture"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
