<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
		xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
		xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
		xmlns:tns="http://www.regione.marche.it/intermediamarche/fatturazione/protocollazione/services"
		xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema"
		name="protocollo"
		targetNamespace="http://www.regione.marche.it/intermediamarche/fatturazione/protocollazione/services">
	<wsdl:types>
		<xsd:schema targetNamespace="http://www.regione.marche.it/intermediamarche/fatturazione/protocollazione/services">
			<xsd:include schemaLocation="../xsd/Segnatura.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="EsitoConsegna">
		<wsdl:part element="tns:EsitoConsegna" name="EsitoConsegna"/>
	</wsdl:message>
	<wsdl:message name="MessaggioProtocollato">
		<wsdl:part name="Segnatura" element="tns:SegnaturaEnvelope"/>
		<wsdl:part name="Allegati" type="xsd:base64Binary"/>
	</wsdl:message>

	<wsdl:portType name="Protocollo">
		<wsdl:operation name="Consegna">
			<wsdl:input message="tns:MessaggioProtocollato"/>
			<wsdl:output message="tns:EsitoConsegna"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="protocolloBinding" type="tns:Protocollo">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="Consegna">
			<soap:operation soapAction="http://www.digitPa.gov.it/protocollo/Consegna"/>
			<wsdl:input>
				<mime:multipartRelated>
					<mime:part>
						<soap:body parts="Segnatura" use="literal"/>
					</mime:part>
					<mime:part>
						<mime:content part="Allegati" type="application/zip"/>
					</mime:part>
				</mime:multipartRelated>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="ProtocolloService">
		<wsdl:port binding="tns:protocolloBinding" name="protocolloService">
			<soap:address location="http://servizioProtocollo.nomeAmministrazione.gov.it"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
