package it.extrasys.marche.regione.fatturapa.mock.sdi.setup;

import it.extrasys.marche.regione.fatturapa.contracts.sdi.ricevinotifica.beans.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-09T15:11:25.640+02:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://setup.sdi.mock.fatturapa.regione.marche.extrasys.it/", name = "ImpostaNotifica")
@XmlSeeAlso({ObjectFactory.class, it.extrasys.marche.regione.fatturapa.contracts.sdi.ricevinotifica.beans.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ImpostaNotifica {

    @WebResult(name = "return", targetNamespace = "http://www.fatturapa.gov.it/sdi/ws/ricezione/v1.0/types", partName = "parameters")
    @WebMethod(operationName = "getNotificaImpostata", action = "http://www.fatturapa.it/SdIRicezioneNotifiche/GetNotificaImpostata")
    public RispostaSdINotificaEsitoType getNotificaImpostata();

    @WebResult(name = "return", targetNamespace = "http://www.fatturapa.gov.it/sdi/ws/ricezione/v1.0/types", partName = "parameters")
    @WebMethod(operationName = "setNotificaImpostata", action = "http://www.fatturapa.it/SdIRicezioneNotifiche/SetNotificaImpostata")
    public RispostaSdINotificaEsitoType setNotificaImpostata(
        @WebParam(partName = "parameters", name = "setNotificaImpostata", targetNamespace = "http://www.fatturapa.gov.it/sdi/ws/ricezione/v1.0/types")
        RispostaSdINotificaEsitoType notifica
    );
    
//    @WebResult(name = "rispostaSdINotificaEsito", targetNamespace = "http://www.fatturapa.gov.it/sdi/ws/ricezione/v1.0/types", partName = "parameters")
//    @WebMethod(operationName = "NotificaEsito", action = "http://www.fatturapa.it/SdIRicezioneNotifiche/NotificaEsito")
//    public RispostaSdINotificaEsitoType notificaEsito(
//        @WebParam(partName = "parameters", name = "fileSdI", targetNamespace = "http://www.fatturapa.gov.it/sdi/ws/ricezione/v1.0/types")
//        FileSdIType parameters
//    );
}
