<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:impl="http://iride.sanitamarche.intra/iride_BHD/services/JBFService"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  targetNamespace="http://iride.sanitamarche.intra/iride_BHD/services/JBFService">
<!--WSDL created by Apache Axis version: 1.4
Built on Oct 06, 2010 (02:39:27 GMT)-->

   <wsdl:message name="callRequest">

      <wsdl:part name="xml" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="callResponse">

      <wsdl:part name="callReturn" type="xsd:string"/>

   </wsdl:message>

   <wsdl:portType name="DefaultWebService">

      <wsdl:operation name="call" parameterOrder="xml">

         <wsdl:input message="impl:callRequest" name="callRequest"/>

         <wsdl:output message="impl:callResponse" name="callResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="JBFServiceSoapBinding" type="impl:DefaultWebService">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="call">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="callRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://services.PSGExt" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="callResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://iride.sanitamarche.intra/iride_BHD/services/JBFService" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="DefaultWebServiceService">

      <wsdl:port binding="impl:JBFServiceSoapBinding" name="JBFService">

         <wsdlsoap:address location="http://iride.sanitamarche.intra/iride_BHD/services/JBFService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
