<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:soapbind="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:types="http://www.extrasys.it/regma/fatturazione/cicloattivo"
        xmlns:tns="http://www.fatturapa.gov.it/sdi/ws/trasmissione/v1.0"
        targetNamespace="http://www.fatturapa.gov.it/sdi/ws/trasmissione/v1.0">

    <!-- TIPI -->
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.extrasys.it/regma/fatturazione/cicloattivo"
                        schemaLocation="../xsd/InoltroFatturazioneAttiva.xsd"/>
        </xsd:schema>
    </wsdl:types>

    <!-- MESSAGGI -->
    <wsdl:message name="RiceviFile_Msg">
        <wsdl:part name="parametersIn" element="types:RiceviFile_Element"/>
    </wsdl:message>

    <wsdl:message name="RispostaRiceviFile_Msg">
        <wsdl:part name="parametersOut" element="types:RispostaRiceviFile_Element"/>
    </wsdl:message>

    <!-- PORT TYPE -->
    <wsdl:portType name="RiceviFile_Port">
        <wsdl:operation name="RiceviFile">
            <wsdl:input message="tns:RiceviFile_Msg"/>
            <wsdl:output message="tns:RispostaRiceviFile_Msg"/>
        </wsdl:operation>
    </wsdl:portType>

    <!-- PORT BINDING -->
    <wsdl:binding name="RiceviFile_binding" type="tns:RiceviFile_Port">
        <soapbind:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="RiceviFile">
            <soapbind:operation soapAction="fatturazioneAttiva/riceviFatture"/>
            <wsdl:input>
                <soapbind:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soapbind:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="RiceviFile_service">
        <wsdl:port name="RiceviFile_Port" binding="tns:RiceviFile_binding">
            <soapbind:address location="http://localhost:8023/ricevi_file"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
