<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="IntermediaMarcheEnteService"
                  targetNamespace="http://www.regione.marche.it/intermediamarche/fatturazione/attiva/registrazione/services"
                  xmlns:apachesoap="http://xml.apache.org/xml-soap"
                  xmlns:tns="http://www.regione.marche.it/intermediamarche/fatturazione/attiva/registrazione/services"
                  xmlns:notif="http://www.regione.marche.it/intermediamarche/fatturazione/attiva/registrazione/services/notifica"
                  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <wsdl:types>
        <xsd:schema elementFormDefault="qualified" targetNamespace="http://www.regione.marche.it/intermediamarche/fatturazione/registrazione/services">
            <xsd:import namespace="http://www.regione.marche.it/intermediamarche/fatturazione/attiva/registrazione/services/notifica" schemaLocation="../xsd/NotificaFatturaAttiva.xsd"/>
        </xsd:schema>
    </wsdl:types>
    
    <wsdl:message name="RiceviNotificaRequest">
        <wsdl:part name="RiceviNotificaRequest" element="notif:Request"/>
    </wsdl:message>
    <wsdl:message name="RiceviNotificaResponse">
        <wsdl:part name="RiceviNotificaResponse" element="notif:Response"/>
    </wsdl:message>
    <wsdl:message name="RiceviNotificaResponseFault">
        <wsdl:part name="Fault" element="notif:FaultDetail" />
    </wsdl:message>

    <wsdl:portType name="IntermediaMarcheEnteServicePort">        
        <wsdl:operation name="RiceviNotifica">
            <wsdl:input message="tns:RiceviNotificaRequest" name="RiceviNotificaRequest"/>
            <wsdl:output message="tns:RiceviNotificaResponse" name="RiceviNotificaResponse"/>
            <wsdl:fault message="tns:RiceviNotificaResponseFault" name="RiceviNotificaResponseFault"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="IntermediaMarcheAttivaEnteServiceSoapBinding" type="tns:IntermediaMarcheEnteServicePort">

        <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="RiceviNotifica">
            <wsdlsoap:operation soapAction="RiceviNotifica"/>
            <wsdl:input name="RiceviNotificaRequest">
                <wsdlsoap:body namespace="http://www.regione.marche.it/intermediamarche/fatturaAttiva/notifiche" use="literal"/>
            </wsdl:input>
            <wsdl:output name="RiceviNotificaResponse">
                <wsdlsoap:body namespace="http://www.regione.marche.it/intermediamarche/fatturaAttiva/notifiche" use="literal"/>
            </wsdl:output>
            <wsdl:fault name="RiceviNotificaResponseFault">
                <wsdlsoap:fault name="RiceviNotificaResponseFault"
                                namespace="http://www.regione.marche.it/intermediaMarche/fatturaAttiva/notifiche" use="literal" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="IntermediaMarcheEnteService">
        <wsdl:port name="IntermediaMarcheEnteServicePort" binding="tns:IntermediaMarcheAttivaEnteServiceSoapBinding">
            <wsdlsoap:address location="http://www.regione.marche.it/intermediaMarche/fatturaAttiva/notifiche"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>